theme: jekyll-theme-dinky
lsi: false
safe: true
source: ComputerGarden95.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
